apiVersion: v1
kind: Service
metadata:
  name: alice
spec:
  type: NodePort
  ports:
  - port: 80
    name: application
  selector:
    app: alice
---
apiVersion: v1
kind: Service
metadata:
  name: bob
spec:
  type: NodePort
  ports:
  - port: 80
    name: application
  selector:
    app: bob
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alice
spec:                                     # Deployment specification
  replicas: 1
  progressDeadlineSeconds: 10
  selector:
    matchLabels:
      app: alice
  template:                               # Pod template
    metadata:
      labels:
        app: alice
    spec:
      imagePullSecrets:
        - name: us-east-2-ecr-registry
      containers:
      - name: flask-buddy                 # Container 1 of 1

        image: 360124560392.dkr.ecr.us-east-2.amazonaws.com/flaskbuddy:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 80
          protocol: TCP
          name: http

        env:
          - name: BUDDY_URI
            value: "http://bob"

        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob
spec:                                     # Deployment specification
  replicas: 1
  progressDeadlineSeconds: 10
  selector:
    matchLabels:
      app: bob
  template:                               # Pod template
    metadata:
      labels:
        app: bob
    spec:
      imagePullSecrets:
        - name: us-east-2-ecr-registry
      containers:
      - name: flask-buddy                 # Container 1 of 1

        image: 360124560392.dkr.ecr.us-east-2.amazonaws.com/flaskbuddy:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 80
          protocol: TCP
          name: http

        env:
          - name: BUDDY_URI
            value: "http://alice:80"

        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
