version: '3.3'
services:
    ann:
        build: .
        ports:
            - "8080:80"
        environment:
            BUDDY_URI: http://bob
    bob:
        build: .
        ports:
            - "8081:80"
        environment: 
            BUDDY_URI: http://ann

