version: '3'
services:
  ann:
    image: 360124560392.dkr.ecr.us-east-2.amazonaws.com/flaskbuddy:latest
    ports:
      - "80"
    environment:
      BUDDY_URI: http://bob

  bob:
    image: 360124560392.dkr.ecr.us-east-2.amazonaws.com/flaskbuddy:latest
    ports:
      - "80"
    environment:
      BUDDY_URI: http://ann
